<a href="https://colab.research.google.com/github/Muhammad-Waleed-Source/Machine-Learning/blob/main/Day-45/Feature-construction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np
import pandas as pd

from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

import seaborn as sns

In [2]:
df = pd.read_csv('train.csv')[['Age','Pclass','SibSp','Parch','Survived']]

In [3]:
df.head()

    Age  Pclass  SibSp  Parch  Survived
0  22.0       3      1      0         0
1  38.0       1      1      0         1
2  26.0       3      0      0         1
3  35.0       1      1      0         1
4  35.0       3      0      0         0

In [4]:
df.dropna(inplace=True)

## Test Train Split

In [5]:
X = df.iloc[:, 0:4]
y = df.iloc[:, -1]

In [7]:
X.head()

    Age  Pclass  SibSp  Parch
0  22.0       3      1      0
1  38.0       1      1      0
2  26.0       3      0      0
3  35.0       1      1      0
4  35.0       3      0      0

In [10]:
np.mean(cross_val_score(LogisticRegression(),X,y,scoring='accuracy',cv=20))

np.float64(0.6933333333333332)

## Applying Feature Construction

In [12]:
X['Family_size'] = X['SibSp'] + X['Parch'] + 1

In [13]:
X.head()

    Age  Pclass  SibSp  Parch  Family_size
0  22.0       3      1      0            2
1  38.0       1      1      0            2
2  26.0       3      0      0            1
3  35.0       1      1      0            2
4  35.0       3      0      0            1

In [14]:
def myfunc(num):
    if num == 1:
        #alone
        return 0
    elif num >1 and num <=4:
        # small family
        return 1
    else:
        # large family
        return 2

In [15]:
myfunc(4)

1

In [16]:
X['Family_type'] = X['Family_size'].apply(myfunc)

In [17]:
X.head()

    Age  Pclass  SibSp  Parch  Family_size  Family_type
0  22.0       3      1      0            2            1
1  38.0       1      1      0            2            1
2  26.0       3      0      0            1            0
3  35.0       1      1      0            2            1
4  35.0       3      0      0            1            0

In [18]:
X.drop(columns=['SibSp','Parch','Family_size'],inplace=True)

In [19]:
X.head()

    Age  Pclass  Family_type
0  22.0       3            1
1  38.0       1            1
2  26.0       3            0
3  35.0       1            1
4  35.0       3            0

In [20]:
np.mean(cross_val_score(LogisticRegression(), X, y, scoring='accuracy', cv=20))

np.float64(0.7003174603174602)

## Feature Splitting

In [21]:
df = pd.read_csv('train.csv')

In [22]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [23]:
df['Name']

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [35]:
df['Title'] = df['Name'].str.split(',', expand=True)[1].str.split(' ', expand=True)[1].str.strip()

In [36]:
df[['Title', 'Name']]

     Title                                               Name
0      Mr.                            Braund, Mr. Owen Harris
1     Mrs.  Cumings, Mrs. John Bradley (Florence Briggs Th...
2    Miss.                             Heikkinen, Miss. Laina
3     Mrs.       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4      Mr.                           Allen, Mr. William Henry
..     ...                                                ...
886   Rev.                              Montvila, Rev. Juozas
887  Miss.                       Graham, Miss. Margaret Edith
888  Miss.           Johnston, Miss. Catherine Helen "Carrie"
889    Mr.                              Behr, Mr. Karl Howell
890    Mr.                                Dooley, Mr. Patrick

[891 rows x 2 columns]

In [40]:
df.groupby('Title')['Survived'].mean().sort_values(ascending=False)

# Mrs and Miss have survival rate of almost 70%

Title
Lady.        1.000000
Ms.          1.000000
Sir.         1.000000
Mme.         1.000000
the          1.000000
Mlle.        1.000000
Mrs.         0.792000
Miss.        0.697802
Master.      0.575000
Major.       0.500000
Col.         0.500000
Dr.          0.428571
Mr.          0.156673
Capt.        0.000000
Jonkheer.    0.000000
Don.         0.000000
Rev.         0.000000
Name: Survived, dtype: float64

In [43]:
df['Is_Married'] = 0

df['Is_Married'].loc[df['Title'] == 'Mrs.'] = 1

/tmp/ipykernel_1018/4251489222.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['Is_Married'].loc[df['Title'] == 'Mrs.'] = 1
/tmp/ipykernel_1018/4251489222.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Is_Married'].loc[df['Title'] == 'Mrs.'] = 1

In [44]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Title,Is_Married
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Mr.,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Mrs.,1
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Miss.,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Mrs.,1
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Mr.,0

In [45]:
df.groupby('Is_Married')['Survived'].mean()

Is_Married
0    0.317232
1    0.792000
Name: Survived, dtype: float64

In [52]:
df = pd.read_csv('/content/deliveries.csv')
df.head()

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN

In [58]:
df2 = pd.DataFrame()

In [65]:
df2['Batsman'] = df['batsman'].value_counts().index

In [66]:
df2.head()

     Batsman
0    V Kohli
1  G Gambhir
2   SK Raina
3  RG Sharma
4   S Dhawan

In [68]:
df2['ball_faced']= df['batsman'].value_counts().values

In [69]:
df2.head()

     Batsman  ball_faced
0    V Kohli        3494
1  G Gambhir        3433
2   SK Raina        3369
3  RG Sharma        3274
4   S Dhawan        3005

In [76]:
df.groupby('batsman')['total_runs'].sum().sort_values(ascending=False)

batsman
SK Raina        4745
V Kohli         4588
G Gambhir       4388
RG Sharma       4334
DA Warner       4213
                ...
L Ablish           0
Abdur Razzak       0
Sunny Gupta        0
IC Pandey          0
U Kaul             0
Name: total_runs, Length: 461, dtype: int64

In [74]:
df2['total_runs'] = df2['Batsman'].map(
    df.groupby('batsman')['total_runs'].sum()
)

In [75]:
df2.head()

     Batsman  ball_faced  total_runs
0    V Kohli        3494        4588
1  G Gambhir        3433        4388
2   SK Raina        3369        4745
3  RG Sharma        3274        4334
4   S Dhawan        3005        3754

In [78]:
(df2['total_runs']/df2['ball_faced']) * 100

0      131.310819
1      127.818235
2      140.842980
3      132.376298
4      124.925125
          ...
456    100.000000
457      0.000000
458    100.000000
459      0.000000
460      0.000000
Length: 461, dtype: float64

In [80]:
df2["strike_rate"] = (df2['total_runs']/df2['ball_faced']) * 100

In [82]:
df2.head()

     Batsman  ball_faced  total_runs  strike_rate
0    V Kohli        3494        4588   131.310819
1  G Gambhir        3433        4388   127.818235
2   SK Raina        3369        4745   140.842980
3  RG Sharma        3274        4334   132.376298
4   S Dhawan        3005        3754   124.925125