<a href="https://colab.research.google.com/github/Muhammad-Waleed-Source/Machine-Learning/blob/main/Day-17/Api-to-dataframe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import requests

In [5]:
response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page=1')

print(response)

<Response [200]>

In [9]:
df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]

,id,title,overview,release_date,popularity,vote_average,vote_count
0,980431,Avatar Aang: The Last Airbender,"Avatar Aang, the world's last Airbender, learn...",2026-07-24,231.0192,9.312,666
1,1632181,Accidental Partners,Two women discover they were both scammed by t...,2026-03-12,24.2800,8.941,339
2,1007757,Swapped,"A small woodland creature and a majestic bird,...",2026-05-01,64.2663,8.891,2054
3,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,75.4156,8.727,30932
4,936075,Michael,"The story of Michael Jackson, one of the most ...",2026-04-22,102.8294,8.698,3860
5,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,58.2728,8.686,23273
6,687163,Project Hail Mary,Science teacher Ryland Grace wakes up on a spa...,2026-03-15,155.5042,8.658,6772
7,1311031,Demon Slayer: Kimetsu no Yaiba Infinity Castle,The Demon Slayer Corps are drawn into the Infi...,2025-07-18,180.3103,8.623,1628
8,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,29.4670,8.570,17690
9,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,36.6553,8.571,14126
10,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,30.4250,8.600,10193
11,155,The Dark Knight,Batman raises the stakes in his war on crime. ...,2008-07-16,61.3967,8.534,36280
12,129,Spirited Away,"A young girl, Chihiro, becomes trapped in a st...",2001-07-20,32.2931,8.534,18633
13,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...",1995-10-20,14.5483,8.507,4607
14,497,The Green Mile,A supernatural tale set on death row in a Sout...,1999-12-10,35.3112,8.506,19552
15,122,The Lord of the Rings: The Return of the King,As armies mass for a final battle that will de...,2003-12-17,54.9695,8.500,26994
16,1218925,Chainsaw Man - The Movie: Reze Arc,"In a brutal war between devils, hunters, and s...",2025-09-19,31.4861,8.499,1073
17,496243,Parasite,"All unemployed, Ki-taek's family takes peculia...",2019-05-30,42.2446,8.489,21007
18,157336,Interstellar,The adventures of a group of explorers who mak...,2014-11-05,73.9896,8.500,40610
19,372058,Your Name.,High schoolers Mitsuha and Taki are complete s...,2016-07-01,27.9000,8.483,12784

In [10]:
df.head()

,id,title,overview,release_date,popularity,vote_average,vote_count
0,980431,Avatar Aang: The Last Airbender,"Avatar Aang, the world's last Airbender, learn...",2026-07-24,231.0192,9.312,666
1,1632181,Accidental Partners,Two women discover they were both scammed by t...,2026-03-12,24.2800,8.941,339
2,1007757,Swapped,"A small woodland creature and a majestic bird,...",2026-05-01,64.2663,8.891,2054
3,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,75.4156,8.727,30932
4,936075,Michael,"The story of Michael Jackson, one of the most ...",2026-04-22,102.8294,8.698,3860

## Fetching all the pages

In [11]:
df = pd.DataFrame()

In [12]:
df

Empty DataFrame
Columns: []
Index: []

In [19]:
for i in range(1, 429):
  response = requests.get(f'https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page={i}')
  temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]
  df = pd.concat([df, temp_df], ignore_index=True)

In [18]:
df.head(50)

# as we can see here that the index starts again from 0 for every page, for that we will use ignore index parameter

,id,title,overview,release_date,popularity,vote_average,vote_count
0,980431,Avatar Aang: The Last Airbender,"Avatar Aang, the world's last Airbender, learn...",2026-07-24,231.0192,9.312,666
1,1632181,Accidental Partners,Two women discover they were both scammed by t...,2026-03-12,24.2800,8.941,339
2,1007757,Swapped,"A small woodland creature and a majestic bird,...",2026-05-01,64.2663,8.891,2054
3,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,75.4156,8.727,30932
4,936075,Michael,"The story of Michael Jackson, one of the most ...",2026-04-22,102.8294,8.698,3860
5,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,58.2728,8.686,23273
6,687163,Project Hail Mary,Science teacher Ryland Grace wakes up on a spa...,2026-03-15,155.5042,8.658,6772
7,1311031,Demon Slayer: Kimetsu no Yaiba Infinity Castle,The Demon Slayer Corps are drawn into the Infi...,2025-07-18,180.3103,8.623,1628
8,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,29.4670,8.570,17690
9,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,36.6553,8.571,14126
10,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,30.4250,8.600,10193
11,155,The Dark Knight,Batman raises the stakes in his war on crime. ...,2008-07-16,61.3967,8.534,36280
12,129,Spirited Away,"A young girl, Chihiro, becomes trapped in a st...",2001-07-20,32.2931,8.534,18633
13,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...",1995-10-20,14.5483,8.507,4607
14,497,The Green Mile,A supernatural tale set on death row in a Sout...,1999-12-10,35.3112,8.506,19552
15,122,The Lord of the Rings: The Return of the King,As armies mass for a final battle that will de...,2003-12-17,54.9695,8.500,26994
16,1218925,Chainsaw Man - The Movie: Reze Arc,"In a brutal war between devils, hunters, and s...",2025-09-19,31.4861,8.499,1073
17,496243,Parasite,"All unemployed, Ki-taek's family takes peculia...",2019-05-30,42.2446,8.489,21007
18,157336,Interstellar,The adventures of a group of explorers who mak...,2014-11-05,73.9896,8.500,40610
19,372058,Your Name.,High schoolers Mitsuha and Taki are complete s...,2016-07-01,27.9000,8.483,12784
0,1330021,Remarkably Bright Creatures,Through unlikely bonds formed during night shi...,2026-05-07,27.2807,8.481,805
1,680,Pulp Fiction,"A burger-loving hit man, his philosophical par...",1994-09-10,41.5572,8.481,30561
2,1383731,Protector,Nikki's life is shattered when her daughter is...,2026-02-20,18.0556,8.471,491
3,429,"The Good, the Bad and the Ugly",While the Civil War rages on between the Union...,1966-12-23,25.0800,8.464,9805
4,13,Forrest Gump,A man with a low IQ has accomplished great thi...,1994-06-23,36.4104,8.464,30124
5,1181678,¿Quieres ser mi hijo?,"Lu, a conformist woman in her forties, learns ...",2023-09-21,9.2240,8.457,362
6,769,GoodFellas,"The true story of Henry Hill, a half-Irish, ha...",1990-09-12,27.3410,8.451,14573
7,346,Seven Samurai,A samurai answers a village's request for prot...,1954-04-26,15.5711,8.400,4298
8,14537,Harakiri,Down-on-his-luck veteran Tsugumo Hanshirō ente...,1962-09-15,10.1754,8.445,1246
9,12477,Grave of the Fireflies,"In the final months of World War II, 14-year-o...",1988-04-16,0.0157,8.443,6647
10,120,The Lord of the Rings: The Fellowship of the Ring,"Young hobbit Frodo Baggins, after inheriting a...",2001-12-18,47.1510,8.440,28005
11,637,Life Is Beautiful,A touching story of an Italian book seller of ...,1997-12-20,21.4711,8.439,14123
12,550,Fight Club,A ticking-time-bomb insomniac and a slippery s...,1999-10-15,54.0542,8.437,32527
13,11216,Cinema Paradiso,"A filmmaker recalls his childhood, when he fel...",1988-11-17,15.7611,8.430,4903
14,598,City of God,In the poverty-stricken favelas of Rio de Jane...,2002-08-30,19.0545,8.429,8314
15,121,The Lord of the Rings: The Two Towers,Frodo Baggins and the other members of the Fel...,2002-12-18,40.4867,8.424,24270
16,40096,A Dog's Will,The lively João Grilo and the sly Chicó are po...,2000-09-15,6.4478,8.414,1233
17,667257,Impossible Things,"After the death of her abusive husband, Matild...",2021-06-17,5.0357,8.413,427
18,539,Psycho,When larcenous real estate clerk Marion Crane ...,1960-06-22,23.0053,8.400,11122
19,510,One Flew Over the Cuckoo's Nest,A petty criminal fakes insanity to serve his s...,1975-11-19,18.4066,8.407,11601
0,255709,Hope,After 8-year-old So-won narrowly survives a br...,2013-10-02,10.3551,8.398,897
1,324857,Spider-Man: Into the Spider-Verse,Struggling to find his place in the world whil...,2018-12-06,69.5475,8.393,17542
2,1891,The Empire Strikes Back,"The epic saga continues as Luke Skywalker, in ...",1980-05-20,21.3265,8.393,18634
3,378064,A Silent Voice: The Movie,Shouya Ishida starts bullying the new girl in ...,2016-09-17,14.3913,8.400,4595
4,4935,Howl's Moving Castle,"Sophie, a young milliner, is turned into an el...",2004-09-09,22.7321,8.388,11263
5,696374,Gabriel's Inferno,An intriguing and sinful exploration of seduct...,2020-05-29,5.2224,8.381,2477
6,807,Se7en,Two homicide detectives are on a desperate hun...,1995-09-22,31.0240,8.381,23452
7,244786,Whiplash,"Under the direction of a ruthless instructor, ...",2014-10-10,32.8265,8.375,16874
8,311,Once Upon a Time in America,A former Prohibition-era Jewish gangster retur...,1984-05-23,19.2399,8.374,6132
9,27205,Inception,"Cobb, a skilled thief who commits corporate es...",2010-07-15,57.2082,8.373,39754

In [20]:
df.head(30)

# now index col is continuous

,id,title,overview,release_date,popularity,vote_average,vote_count
0,980431,Avatar Aang: The Last Airbender,"Avatar Aang, the world's last Airbender, learn...",2026-07-24,231.0192,9.312,666
1,1632181,Accidental Partners,Two women discover they were both scammed by t...,2026-03-12,24.2800,8.941,339
2,1007757,Swapped,"A small woodland creature and a majestic bird,...",2026-05-01,64.2663,8.891,2054
3,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,75.4156,8.727,30932
4,936075,Michael,"The story of Michael Jackson, one of the most ...",2026-04-22,102.8294,8.698,3860
5,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,58.2728,8.686,23273
6,687163,Project Hail Mary,Science teacher Ryland Grace wakes up on a spa...,2026-03-15,155.5042,8.658,6772
7,1311031,Demon Slayer: Kimetsu no Yaiba Infinity Castle,The Demon Slayer Corps are drawn into the Infi...,2025-07-18,180.3103,8.623,1628
8,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,29.4670,8.570,17690
9,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,36.6553,8.571,14126
10,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,30.4250,8.600,10193
11,155,The Dark Knight,Batman raises the stakes in his war on crime. ...,2008-07-16,61.3967,8.534,36280
12,129,Spirited Away,"A young girl, Chihiro, becomes trapped in a st...",2001-07-20,32.2931,8.534,18633
13,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...",1995-10-20,14.5483,8.507,4607
14,497,The Green Mile,A supernatural tale set on death row in a Sout...,1999-12-10,35.3112,8.506,19552
15,122,The Lord of the Rings: The Return of the King,As armies mass for a final battle that will de...,2003-12-17,54.9695,8.500,26994
16,1218925,Chainsaw Man - The Movie: Reze Arc,"In a brutal war between devils, hunters, and s...",2025-09-19,31.4861,8.499,1073
17,496243,Parasite,"All unemployed, Ki-taek's family takes peculia...",2019-05-30,42.2446,8.489,21007
18,157336,Interstellar,The adventures of a group of explorers who mak...,2014-11-05,73.9896,8.500,40610
19,372058,Your Name.,High schoolers Mitsuha and Taki are complete s...,2016-07-01,27.9000,8.483,12784
20,1330021,Remarkably Bright Creatures,Through unlikely bonds formed during night shi...,2026-05-07,27.2807,8.481,805
21,680,Pulp Fiction,"A burger-loving hit man, his philosophical par...",1994-09-10,41.5572,8.481,30561
22,1383731,Protector,Nikki's life is shattered when her daughter is...,2026-02-20,18.0556,8.471,491
23,429,"The Good, the Bad and the Ugly",While the Civil War rages on between the Union...,1966-12-23,25.0800,8.464,9805
24,13,Forrest Gump,A man with a low IQ has accomplished great thi...,1994-06-23,36.4104,8.464,30124
25,1181678,¿Quieres ser mi hijo?,"Lu, a conformist woman in her forties, learns ...",2023-09-21,9.2240,8.457,362
26,769,GoodFellas,"The true story of Henry Hill, a half-Irish, ha...",1990-09-12,27.3410,8.451,14573
27,346,Seven Samurai,A samurai answers a village's request for prot...,1954-04-26,15.5711,8.400,4298
28,14537,Harakiri,Down-on-his-luck veteran Tsugumo Hanshirō ente...,1962-09-15,10.1754,8.445,1246
29,12477,Grave of the Fireflies,"In the final months of World War II, 14-year-o...",1988-04-16,0.0157,8.443,6647

In [22]:
df.shape

(17120, 7)

In [23]:
df.to_csv('movies.csv')